<img align="left" src="https://lever-client-logos.s3.amazonaws.com/864372b1-534c-480e-acd5-9711f850815c-1524247202159.png" width=200>
<br></br>
<br></br>

## *Data Science Unit 4 Sprint 2*

# Sprint Challenge - Neural Network Foundations

Table of Problems

1. [Defining Neural Networks](#Q1)
2. [Chocolate Gummy Bears](#Q2)
    - Perceptron
    - Multilayer Perceptron
4. [Keras MMP](#Q3)

<a id="Q1"></a>
## 1. Define the following terms:

- **Neuron:** units in a neural network that recieve inputs from other nodes or an external source to compute an output
- **Input Layer:** data collected for each of the independent variables. X1,X2,X3 and so on
- **Hidden Layer:** layers between inputs and out put with different itterations definging the weights a biases for selected input to achieve desired output
- **Output Layer:** information displayed to us after defining the input and adjusting how the hidden layers will work.
- **Activation:** a non-linier function that take the inputs of a NN and defines the oputput
- **Backpropagation:** helps weights adjust effectively after learning the mistake enhance to a better score


## 2. Chocolate Gummy Bears <a id="Q2"></a>

Right now, you're probably thinking, "yuck, who the hell would eat that?". Great question. Your candy company wants to know too. And you thought I was kidding about the [Chocolate Gummy Bears](https://nuts.com/chocolatessweets/gummies/gummy-bears/milk-gummy-bears.html?utm_source=google&utm_medium=cpc&adpos=1o1&gclid=Cj0KCQjwrfvsBRD7ARIsAKuDvMOZrysDku3jGuWaDqf9TrV3x5JLXt1eqnVhN0KM6fMcbA1nod3h8AwaAvWwEALw_wcB). 

Let's assume that a candy company has gone out and collected information on the types of Halloween candy kids ate. Our candy company wants to predict the eating behavior of witches, warlocks, and ghosts -- aka costumed kids. They shared a sample dataset with us. Each row represents a piece of candy that a costumed child was presented with during "trick" or "treat". We know if the candy was `chocolate` (or not chocolate) or `gummy` (or not gummy). Your goal is to predict if the costumed kid `ate` the piece of candy. 

If both chocolate and gummy equal one, you've got a chocolate gummy bear on your hands!?!?!
![Chocolate Gummy Bear](https://ed910ae2d60f0d25bcb8-80550f96b5feb12604f4f720bfefb46d.ssl.cf1.rackcdn.com/3fb630c04435b7b5-2leZuM7_-zoom.jpg)

In [1]:
import pandas as pd
candy = pd.read_csv('chocolate_gummy_bears.csv')

In [2]:
candy.head()

chocolate  gummy  ate
0          0      1    1
1          1      0    1
2          0      1    1
3          0      0    0
4          1      1    0

### Perceptron

To make predictions on the `candy` dataframe. Build and train a Perceptron using numpy. Your target column is `ate` and your features: `chocolate` and `gummy`. Do not do any feature engineering. :P

Once you've trained your model, report your accuracy. You will not be able to achieve more than ~50% with the simple perceptron. Explain why you could not achieve a higher accuracy with the *simple perceptron* architecture, because it's possible to achieve ~95% accuracy on this dataset. Provide your answer in markdown (and *optional* data anlysis code) after your perceptron implementation. 

In [3]:
# Start your candy perceptron here

X = candy[['chocolate', 'gummy']].values
y = candy['ate'].values

In [4]:
import numpy as np

def sigmoid(x):
    return 1 / (1 + np.exp(-x))

def sigmoid_derivate(x):
    sx = sigmoid(x)
    return( sx * (1-sx))

class Perceptron(object):
    
    def __init__(self, niter = 1):
        self.niter = niter
    

    def fit(self, X, y):
        
        inputs = X
        correct_outputs = y.reshape(-1,1)

        weights = 2 * np.random.random((X.shape[1],1)) - 1
       # bias = 2 * np.random.random((len(X),1)) - 1
        
        for i in range(self.niter):

            weighted_sum = np.dot(inputs, weights)# + bias

            activated_output = sigmoid(weighted_sum)

   
            error = correct_outputs - activated_output

            adjustments = error * sigmoid_derivate(activated_output)

  
            #bias += error
            weights += np.dot(inputs.T, adjustments)
        self.activated_output = activated_output
        self.weights = weights
        #self.bias = bias
        

    def predict(self, X):
        weighted_sum = np.dot(X, self.weights) #+ self.bias
        
        return sigmoid(weighted_sum)

In [5]:
nn = Perceptron()
nn.fit(X,y)

In [6]:
pred = nn.predict(X)

n_pred = []
for i in pred:
    n_pred.append(int(i))
from sklearn.metrics import accuracy_score as acs

acs(y, n_pred)

0.5

a simple perceptron does not have the bias nor does it have weights updated effictively.

### Multilayer Perceptron <a id="Q3"></a>

Using the sample candy dataset, implement a Neural Network Multilayer Perceptron class that uses backpropagation to update the network's weights. Your Multilayer Perceptron should be implemented in Numpy. 
Your network must have one hidden layer.

Once you've trained your model, report your accuracy. Explain why your MLP's performance is considerably better than your simple perceptron's on the candy dataset. 

In [7]:
class NeuralNetwork:
    def __init__(self):

        self.inputs = 2
        self.hiddenNodes = 3
        self.outputNodes = 1


        self.weights1 = np.random.rand(self.inputs, self.hiddenNodes)
        self.weights2 = np.random.rand(self.hiddenNodes, self.outputNodes)
        
    def sigmoid(self, s):
        return 1 / (1+np.exp(-s))
    
    def sigmoidPrime(self, s):
        return s * (1 - s)
    
    def feed_forward(self, X):

        self.hidden_sum = np.dot(X, self.weights1)

        self.activated_hidden = self.sigmoid(self.hidden_sum)
        self.output_sum = np.dot(self.activated_hidden, self.weights2)
        self.activated_output = self.sigmoid(self.output_sum)
        
        return self.activated_output
        
    def backward(self, X,y,o):

        self.o_error = y - o
        self.o_delta = self.o_error * self.sigmoidPrime(o)
        self.z2_error = self.o_delta.dot(self.weights2.T)
        self.z2_delta = self.z2_error * self.sigmoidPrime(self.activated_hidden)
        self.weights1 += X.T.dot(self.z2_delta)
        self.weights2 += self.activated_hidden.T.dot(self.o_delta)
        

    def train(self, X, y):
        o = self.feed_forward(X)
        self.backward(X,y,o)

nn = NeuralNetwork()

y.reshape(-1,1)

array([[1],
       [1],
       [1],
       ...,
       [1],
       [1],
       [1]], dtype=int64)

In [8]:
for i in range(10000):
    if (i in [a for a in range(7)]) or ((i + 1) % 5000 == 0):
        print('+' + '---' * 3 + f'EPOCH {i+1}' + '---'*3 + '+')
        print('Input: \n', X)
        print('Actual Output: \n', y.reshape(-1,1))
        print('Predicted Output: \n', str(nn.feed_forward(X)))
        print("Loss: \n", str(np.mean(np.square(y.reshape(-1,1) - nn.feed_forward(X)))))
    nn.train(X,y.reshape(-1,1))

+---------EPOCH 1---------+
Input: 
 [[0 1]
 [1 0]
 [0 1]
 ...
 [0 1]
 [0 1]
 [1 0]]
Actual Output: 
 [[1]
 [1]
 [1]
 ...
 [1]
 [1]
 [1]]
Predicted Output: 
 [[0.73721163]
 [0.7267955 ]
 [0.73721163]
 ...
 [0.73721163]
 [0.73721163]
 [0.7267955 ]]
Loss: 
 0.3030801915393845
+---------EPOCH 2---------+
Input: 
 [[0 1]
 [1 0]
 [0 1]
 ...
 [0 1]
 [0 1]
 [1 0]]
Actual Output: 
 [[1]
 [1]
 [1]
 ...
 [1]
 [1]
 [1]]
Predicted Output: 
 [[0.4999969 ]
 [0.49999178]
 [0.4999969 ]
 ...
 [0.4999969 ]
 [0.4999969 ]
 [0.49999178]]
Loss: 
 0.2011525223324958
+---------EPOCH 3---------+
Input: 
 [[0 1]
 [1 0]
 [0 1]
 ...
 [0 1]
 [0 1]
 [1 0]]
Actual Output: 
 [[1]
 [1]
 [1]
 ...
 [1]
 [1]
 [1]]
Predicted Output: 
 [[0.49999691]
 [0.49999183]
 [0.49999691]
 ...
 [0.49999691]
 [0.49999691]
 [0.49999183]]
Loss: 
 0.2011525082329036
+---------EPOCH 4---------+
Input: 
 [[0 1]
 [1 0]
 [0 1]
 ...
 [0 1]
 [0 1]
 [1 0]]
Actual Output: 
 [[1]
 [1]
 [1]
 ...
 [1]
 [1]
 [1]]
Predicted Output: 
 [[0.49999692]
 [0

In [13]:
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

def sigmoid_derivate(x):
    sx = sigmoid(x)
    return( sx * (1-sx))

class Perceptron(object):
    
    def __init__(self, niter = 500):
        self.niter = niter
    

    def fit(self, X, y):
        
        inputs = X
        correct_outputs = y.reshape(-1,1)

        weights = 2 * np.random.random((X.shape[1],1)) - 1
        bias = 2 * np.random.random((len(X),1)) - 1
        
        for i in range(self.niter):

            weighted_sum = np.dot(inputs, weights) + bias

            activated_output = sigmoid(weighted_sum)

   
            error = correct_outputs - activated_output

            adjustments = error * sigmoid_derivate(activated_output)

  
            bias += error
            weights += np.dot(inputs.T, adjustments)
        self.activated_output = activated_output
        self.weights = weights
        self.bias = bias
        

    def predict(self, X):
        weighted_sum = np.dot(X, self.weights) + self.bias
        
        return sigmoid(weighted_sum)


nn = Perceptron()
nn.fit(X,y)


pred = nn.predict(X)
n_pred = []
for i in pred:
    n_pred.append(int(i))

acs(y,n_pred)

0.9859

Backpropogation helps weights adjust effectively after learning the mistake enhance to a better score (+95%)

P.S. Don't try candy gummy bears. They're disgusting. 

## 3. Keras MMP <a id="Q3"></a>

Implement a Multilayer Perceptron architecture of your choosing using the Keras library. Train your model and report its baseline accuracy. Then hyperparameter tune at least two parameters and report your model's accuracy.
Use the Heart Disease Dataset (binary classification)
Use an appropriate loss function for a binary classification task
Use an appropriate activation function on the final layer of your network.
Train your model using verbose output for ease of grading.
Use GridSearchCV or RandomSearchCV to hyperparameter tune your model. (for at least two hyperparameters)
When hyperparameter tuning, show you work by adding code cells for each new experiment.
Report the accuracy for each combination of hyperparameters as you test them so that we can easily see which resulted in the highest accuracy.
You must hyperparameter tune at least 3 parameters in order to get a 3 on this section.

In [14]:
import pandas as pd
from sklearn.preprocessing import StandardScaler

df = pd.read_csv('https://raw.githubusercontent.com/ryanleeallred/datasets/master/heart.csv')
df = df.sample(frac=1)
print(df.shape)
df.head()

(303, 14)


age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  \
81    45    1   1       128   308    0        0      170      0      0.0   
38    65    0   2       155   269    0        1      148      0      0.8   
173   58    1   2       132   224    0        0      173      0      3.2   
275   52    1   0       125   212    0        1      168      0      1.0   
227   35    1   0       120   198    0        1      130      1      1.6   

     slope  ca  thal  target  
81       2   0     2       1  
38       2   0     2       1  
173      2   2     3       0  
275      2   2     3       0  
227      1   0     3       0

In [15]:
!pip install keras

In [16]:
!pip install tensorflow

In [17]:
import sklearn
from sklearn.model_selection import GridSearchCV, train_test_split
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout
from tensorflow.keras.wrappers.scikit_learn import KerasClassifier

X = df.iloc[:,0:14]
y = df.values[:,-1].astype('bool')

print(X.shape,y.shape)

(303, 14) (303,)


In [18]:
names = X.columns# Create the Scaler object
scaler = StandardScaler()# Fit your data on the scaler object
scaled_X = scaler.fit_transform(X)
X = pd.DataFrame(scaled_X, columns=names)

In [19]:
df.target.value_counts(normalize = True)

1    0.544554
0    0.455446
Name: target, dtype: float64

In [20]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=.2)
print(X_train.shape, y_train.shape, X_test.shape, y_test.shape)

(242, 14) (242,) (61, 14) (61,)


In [21]:
#Frame the model

import numpy as np
# Plant a random seed for reproducibility
seed = 1
np.random.seed(seed)

# Function to create model, required for KerasClassifier
def create_model():
# create model - Sigmoid activation function for binary/boolean type
    model = Sequential()
    model.add(Dense(24, input_dim=14, activation='sigmoid'))
    model.add(Dropout(rate = .3))
    model.add(Dense(12, activation='sigmoid'))
    model.add(Dense(1, activation='sigmoid'))
    
    # Compile model
    model.compile(loss='binary_crossentropy',
                  optimizer='adam',
                  metrics=['accuracy'])
    return model

# create model; verbose? Yes
model = KerasClassifier(build_fn=create_model, verbose=1)

# define the grid search parameters; Bests: batch_size = , epochs = 
param_grid = {'batch_size': [1,10,30,60,120],  
              'epochs': [10]
             } 

# Create Grid Search
grid = GridSearchCV(estimator=model, param_grid=param_grid, n_jobs=-1)

grid_result = grid.fit(X_train, y_train)

# Report Results - best accuracy = 
print(f"Best: {grid_result.best_score_} using {grid_result.best_params_}")
means = grid_result.cv_results_['mean_test_score']
stds = grid_result.cv_results_['std_test_score']
params = grid_result.cv_results_['params']
for mean, stdev, param in zip(means, stds, params):
    print(f"Means: {mean}, Stdev: {stdev} with: {param}")

C:\Users\tako\Anaconda3\lib\site-packages\sklearn\model_selection\_split.py:1978: FutureWarning: The default value of cv will change from 3 to 5 in version 0.22. Specify it explicitly to silence this warning.
  warnings.warn(CV_WARNING, FutureWarning)


C:\Users\tako\Anaconda3\lib\site-packages\sklearn\model_selection\_search.py:813: DeprecationWarning: The default of the `iid` parameter will change from True to False in version 0.22 and will be removed in 0.24. This will change numeric results when test-set sizes are unequal.
  DeprecationWarning)


Train on 242 samples
Epoch 1/10
242/242 [==============================] - 0s 1ms/sample - loss: 0.7114 - accuracy: 0.5455
Epoch 2/10
242/242 [==============================] - 0s 959us/sample - loss: 0.5646 - accuracy: 0.7934
Epoch 3/10
242/242 [==============================] - 0s 897us/sample - loss: 0.4430 - accuracy: 0.9174
Epoch 4/10
242/242 [==============================] - 0s 835us/sample - loss: 0.3306 - accuracy: 0.9380
Epoch 5/10
242/242 [==============================] - 0s 814us/sample - loss: 0.2179 - accuracy: 0.9793
Epoch 6/10
242/242 [==============================] - 0s 851us/sample - loss: 0.1618 - accuracy: 0.9793
Epoch 7/10
242/242 [==============================] - 0s 835us/sample - loss: 0.1196 - accuracy: 0.9835
Epoch 8/10
242/242 [==============================] - 0s 864us/sample - loss: 0.0948 - accuracy: 0.9876
Epoch 9/10
242/242 [==============================] - 0s 921us/sample - loss: 0.0603 - accuracy: 0.9959
Epoch 10/10
242/242 [========================

In [22]:
#trying a higher batch size for better accuracy

# define the grid search parameters; Bests: batch_size = , epochs = 
param_grid = {'batch_size': [120],  
              'epochs': [10, 20, 40, 80, 160]
             }

# Create Grid Search
grid = GridSearchCV(estimator=model, param_grid=param_grid, n_jobs=-1)

grid_result = grid.fit(X_train, y_train)

# Report Results - best accuracy = 
print(f"Best: {grid_result.best_score_} using {grid_result.best_params_}")
means = grid_result.cv_results_['mean_test_score']
stds = grid_result.cv_results_['std_test_score']
params = grid_result.cv_results_['params']
for mean, stdev, param in zip(means, stds, params):
    print(f"Means: {mean}, Stdev: {stdev} with: {param}")

C:\Users\tako\Anaconda3\lib\site-packages\sklearn\model_selection\_search.py:813: DeprecationWarning: The default of the `iid` parameter will change from True to False in version 0.22 and will be removed in 0.24. This will change numeric results when test-set sizes are unequal.
  DeprecationWarning)


Train on 242 samples
Epoch 1/160
242/242 [==============================] - 0s 421us/sample - loss: 0.6769 - accuracy: 0.5661
Epoch 2/160
242/242 [==============================] - 0s 25us/sample - loss: 0.6746 - accuracy: 0.5785
Epoch 3/160
242/242 [==============================] - 0s 25us/sample - loss: 0.6706 - accuracy: 0.6033
Epoch 4/160
242/242 [==============================] - 0s 25us/sample - loss: 0.6621 - accuracy: 0.6777
Epoch 5/160
242/242 [==============================] - 0s 25us/sample - loss: 0.6593 - accuracy: 0.6529
Epoch 6/160
242/242 [==============================] - 0s 25us/sample - loss: 0.6660 - accuracy: 0.6281
Epoch 7/160
242/242 [==============================] - 0s 29us/sample - loss: 0.6626 - accuracy: 0.6281
Epoch 8/160
242/242 [==============================] - 0s 29us/sample - loss: 0.6552 - accuracy: 0.6364
Epoch 9/160
242/242 [==============================] - 0s 29us/sample - loss: 0.6497 - accuracy: 0.6405
Epoch 10/160
242/242 [====================

242/242 [==============================] - 0s 21us/sample - loss: 0.4455 - accuracy: 0.8926
Epoch 79/160
242/242 [==============================] - 0s 25us/sample - loss: 0.4280 - accuracy: 0.9008
Epoch 80/160
242/242 [==============================] - 0s 21us/sample - loss: 0.4285 - accuracy: 0.8967
Epoch 81/160
242/242 [==============================] - 0s 21us/sample - loss: 0.4247 - accuracy: 0.9050
Epoch 82/160
242/242 [==============================] - 0s 25us/sample - loss: 0.4266 - accuracy: 0.8802
Epoch 83/160
242/242 [==============================] - 0s 25us/sample - loss: 0.4242 - accuracy: 0.9050
Epoch 84/160
242/242 [==============================] - 0s 21us/sample - loss: 0.4261 - accuracy: 0.9008
Epoch 85/160
242/242 [==============================] - 0s 25us/sample - loss: 0.4239 - accuracy: 0.8884
Epoch 86/160
242/242 [==============================] - 0s 25us/sample - loss: 0.3991 - accuracy: 0.9215
Epoch 87/160
242/242 [==============================] - 0s 29us/samp

242/242 [==============================] - 0s 29us/sample - loss: 0.2456 - accuracy: 0.9463
Epoch 156/160
242/242 [==============================] - 0s 33us/sample - loss: 0.2273 - accuracy: 0.9669
Epoch 157/160
242/242 [==============================] - 0s 25us/sample - loss: 0.2261 - accuracy: 0.9669
Epoch 158/160
242/242 [==============================] - 0s 41us/sample - loss: 0.2262 - accuracy: 0.9587
Epoch 159/160
242/242 [==============================] - 0s 29us/sample - loss: 0.2162 - accuracy: 0.9587
Epoch 160/160
242/242 [==============================] - 0s 29us/sample - loss: 0.2315 - accuracy: 0.9380
Best: 0.9462809914892371 using {'batch_size': 120, 'epochs': 160}
Means: 0.5743801617179035, Stdev: 0.09596058826285811 with: {'batch_size': 120, 'epochs': 10}
Means: 0.6074380132038731, Stdev: 0.12830382245039068 with: {'batch_size': 120, 'epochs': 20}
Means: 0.7355371969790498, Stdev: 0.09736470980272625 with: {'batch_size': 120, 'epochs': 40}
Means: 0.8842975359317685, Std

In [23]:
#refining epoch values

# define the grid search parameters; Bests: batch_size = , epochs = 
param_grid = {'batch_size': [120],  
              'epochs': [30, 40, 50, 60, 70]
             }

# Create Grid Search
grid = GridSearchCV(estimator=model, param_grid=param_grid, n_jobs=-1)

grid_result = grid.fit(X_train, y_train)

# Report Results - best accuracy = 
print(f"Best: {grid_result.best_score_} using {grid_result.best_params_}")
means = grid_result.cv_results_['mean_test_score']
stds = grid_result.cv_results_['std_test_score']
params = grid_result.cv_results_['params']
for mean, stdev, param in zip(means, stds, params):
    print(f"Means: {mean}, Stdev: {stdev} with: {param}")

C:\Users\tako\Anaconda3\lib\site-packages\sklearn\model_selection\_search.py:813: DeprecationWarning: The default of the `iid` parameter will change from True to False in version 0.22 and will be removed in 0.24. This will change numeric results when test-set sizes are unequal.
  DeprecationWarning)


Train on 242 samples
Epoch 1/70
242/242 [==============================] - 0s 479us/sample - loss: 0.7114 - accuracy: 0.5248
Epoch 2/70
242/242 [==============================] - 0s 21us/sample - loss: 0.7060 - accuracy: 0.5041
Epoch 3/70
242/242 [==============================] - 0s 29us/sample - loss: 0.7062 - accuracy: 0.5248
Epoch 4/70
242/242 [==============================] - 0s 25us/sample - loss: 0.7053 - accuracy: 0.5000
Epoch 5/70
242/242 [==============================] - 0s 29us/sample - loss: 0.7002 - accuracy: 0.5248
Epoch 6/70
242/242 [==============================] - 0s 21us/sample - loss: 0.6886 - accuracy: 0.5248
Epoch 7/70
242/242 [==============================] - 0s 25us/sample - loss: 0.6882 - accuracy: 0.5413
Epoch 8/70
242/242 [==============================] - 0s 37us/sample - loss: 0.6865 - accuracy: 0.5579
Epoch 9/70
242/242 [==============================] - 0s 29us/sample - loss: 0.6838 - accuracy: 0.5620
Epoch 10/70
242/242 [==============================